version: '3.9'  # Latest stable Docker Compose version

services:
  # MongoDB database service
  mongodb:
    image: mongo:6         # Use a stable MongoDB version
    container_name: mongodb
    restart: unless-stopped  # Restart automatically unless manually stopped
    ports:
      - "27017:27017"      # Map host port 27017 to container port 27017
    environment:
      # Set root username and password for MongoDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      # Persist MongoDB data in a named volume so data is retained across container restarts
      - mongo-data:/data/db
    healthcheck:
      # Ensure MongoDB is healthy before other services that depend on it start
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s        # Time between healthchecks
      timeout: 5s          # Time before healthcheck times out
      retries: 5           # Number of retries before marking service as unhealthy

  # Mongo Express web UI service for MongoDB
  mongo-express:
    image: mongo-express:1.0.0  # Pin a stable version
    container_name: mongo-express
    restart: unless-stopped       # Restart automatically unless manually stopped
    ports:
      - "8080:8081"              # Map container port 8081 to host port 8080
    environment:
      # MongoDB admin credentials for connecting via Mongo Express
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb  # Use MongoDB container name as host
      ME_CONFIG_OPTIONS_EDITORTHEME: default  # Optional: set editor theme
    depends_on:
      # Ensure Mongo Express starts only after MongoDB is healthy
      mongodb:
        condition: service_healthy

# Named volume for persisting MongoDB data
volumes:
  mongo-data:
    driver: local  # Use local storage on the host
